# Generated by Django 5.2.11 on 2026-04-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_name_movie_title_remove_movie_cast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Paste the full YouTube video URL here (e.g. https://www.youtube.com/watch?v=abc123)', null=True),
        ),
    ]
